# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator', '0002_remove_investigator_fotoperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigator',
            name='facebook',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='investigator',
            name='googlePlus',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='investigator',
            name='twitter',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
