# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator', '0004_investigator_fotoperfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigator',
            name='activo',
            field=models.BooleanField(default=1),
        ),
    ]
